Repository mlargeot/Area, pull requests merged in 2024-12, with the labels that each got.

#35 merge(dev) merge feature/back-docker into dev
  .gitignore
  .idea/.gitignore
  .idea/Area.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/jsLinters/eslint.xml
  .idea/modules.xml
  .idea/vcs.xml
  backend/.env.example
  backend/.env.template
  backend/Dockerfile
  backend/src/app.module.ts
  docker-compose-mongodb.yml
  docker-compose.yml
Labels: ⚙️ build

#37 merge(dev): feature/github-oauth into dev
  .gitignore
  backend/package.json
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/strategies/github.startegy.ts
  backend/yarn.lock
Labels: ✨ enhancement

#38 merge(dev): merge feat-backend-actions into dev branch
  .gitignore
  backend/src/about/about.module.ts
  backend/src/about/about.service.ts
  backend/src/actions/actions.controller.ts
  backend/src/actions/actions.module.ts
  backend/src/actions/actions.service.ts
  backend/src/actions/dto/default_actions.dto.ts
  backend/src/app.module.ts
  backend/src/auth/dto/create-user.dto.ts
  backend/src/auth/dto/login-user.dto.ts
  backend/src/reactions/dto/default_reactions.dto.ts
  backend/src/reactions/reactions.controller.ts
  backend/src/reactions/reactions.module.ts
  backend/src/reactions/reactions.service.ts
Labels: ✨ enhancement

#41 merge(dev): merge feat-backend-applet into dev
  README.md
  backend/package.json
  backend/src/reactions/discord/r_discord.module.ts
  backend/src/reactions/discord/r_discord.service.ts
  backend/src/reactions/reactions.module.ts
  backend/src/reactions/reactions.service.ts
  backend/yarn.lock
  docs/README_API.md
Labels: 📝 documentation, ✨ enhancement

#42 merge(dev): feature/github_webhook into dev
  backend/src/actions/actions.module.ts
  backend/src/actions/github/github.actions.controller.ts
  backend/src/actions/github/github.actions.module.ts
  backend/src/actions/github/github.actions.service.ts
Labels: ✨ enhancement

#53 merge (dev) : merge Feat/frontend into dev
  backend/src/app.module.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/main.ts
  backend/src/services/dto/add-service.dto.ts
  backend/src/services/services.controller.ts
  backend/src/services/services.module.ts
  backend/src/services/services.service.ts
  frontend/.env.template
  frontend/.gitignore
  frontend/Dockerfile
  frontend/__tests__/App.test.tsx
  frontend/app.json
  frontend/app/(auth)/ask-4-reset-password.tsx
  frontend/app/(auth)/auth-handler.tsx
  frontend/app/(auth)/components/signup.tsx
  frontend/app/(auth)/login.tsx
  frontend/app/(auth)/register.tsx
  frontend/app/(auth)/reset-password.tsx
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/app/(protected)/(tabs)/profile.tsx
  frontend/app/(protected)/Pages/Create/actions.tsx
  frontend/app/(protected)/Pages/Create/form.tsx
  frontend/app/(protected)/Pages/Create/reactions.tsx
  frontend/app/(protected)/Pages/Create/services.tsx
  frontend/app/(protected)/Pages/services.tsx
  frontend/app/(protected)/_layout.tsx
  frontend/app/context/appletContext.tsx
  frontend/app/index.tsx
  frontend/assets/adaptive-icon.png
  frontend/assets/favicon.png
  frontend/assets/icon.png
  frontend/assets/splash-icon.png
  frontend/assets/splash.png
  frontend/components/forgotpassword.tsx
  frontend/components/login.tsx
  frontend/components/signup.tsx
  frontend/hooks/useAuth.ts
  frontend/package-lock.json
  frontend/package.json
  frontend/routes/protectedRoute.tsx
  frontend/tsconfig.json
Labels: ✨ enhancement, 🔨 fix

#59 merge(dev): feature/ar3m_ci into dev
  .github/workflows/ar3m_ci.yml
  backend/package-lock.json
  backend/yarn.lock
Labels: ⚙️ build

#64 merge(dev): merge feat/frontend into dev
  frontend/Dockerfile
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/app/(protected)/(tabs)/profile.tsx
  frontend/app/(protected)/Create/action/effect.tsx
  frontend/app/(protected)/Create/action/form.tsx
  frontend/app/(protected)/Create/reaction/effect.tsx
  frontend/app/(protected)/Create/reaction/form.tsx
  frontend/app/(protected)/Create/services.tsx
  frontend/app/(protected)/Pages/Create/reactions.tsx
  frontend/app/(protected)/Pages/Create/services.tsx
  frontend/app/(protected)/services.tsx
  frontend/app/_layout.tsx
  frontend/app/context/navigationContext.tsx
  frontend/components/actionButton.tsx
  frontend/components/reactionButton.tsx
  frontend/context/appletContext.tsx
  frontend/context/navigationContext.tsx
  frontend/context/serviceListContext.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: ✨ enhancement, 🔨 fix
