Repository mlargeot/Area, pull requests merged in 2025-01, with the labels that each got.

#68 merge feat/frontend into dev
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/app/(protected)/Create/action/effect.tsx
  frontend/app/(protected)/Create/reaction/effect.tsx
  frontend/app/(protected)/Create/reaction/form.tsx
  frontend/app/(protected)/Create/services.tsx
  frontend/app/_layout.tsx
  frontend/components/actionButton.tsx
  frontend/components/reactionButton.tsx
  frontend/context/navigationContext.tsx
  frontend/context/serviceListContext.tsx
  frontend/package-lock.json
  frontend/package.json
Labels: 🔨 fix

#69 merge(dev): merge feat/frontend into dev
  frontend/app/(protected)/Create/reaction/form.tsx
Labels: ✨ enhancement

#70 merge(dev): merge applet-logic into dev
  backend/.env.example
  backend/src/applets/applets.controller.ts
  backend/src/applets/applets.service.ts
  backend/src/applets/dto/applets.dto.ts
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/provider-dto.ts
  backend/src/auth/state.store.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/github.action.service.ts
  backend/src/main.ts
  backend/src/schemas/applet.schema.ts
  backend/src/utils/logger.ts
  backend/src/webhooks/webhook.controller.ts
  backend/src/webhooks/webhook.service.ts
  frontend/app/(auth)/auth-handler.tsx
  frontend/app/(auth)/auth/callback.tsx
  frontend/app/(protected)/(tabs)/_layout.tsx
  frontend/app/(protected)/(tabs)/logs.tsx
  frontend/app/(protected)/services.tsx
  frontend/app/index.tsx
  frontend/components/login.test.tsx
  frontend/components/login.test2.tsx
  frontend/components/login.tsx
  frontend/hooks/connectService.ts
  frontend/hooks/loginService.ts
  frontend/hooks/useAuth.ts
  frontend/index.js
  frontend/package-lock.json
  frontend/package.json
Labels: 📝 documentation, ✨ enhancement

#77 merge(feat/library_page): merge feat/library_page into dev
  frontend/app/(protected)/(tabs)/_layout.tsx
  frontend/app/(protected)/(tabs)/library.tsx
  frontend/app/(protected)/Create/action/form.tsx
  frontend/app/(protected)/Create/reaction/form.tsx
  frontend/components/descriptionHelpButton.tsx
  frontend/context/serviceListContext.tsx
Labels: ✨ enhancement

#79 merge(dev): merge services-description into dev
  backend/src/about/about.service.ts
  backend/src/automation/automation.module.ts
  backend/src/automation/controllers/actions.controller.ts
  backend/src/automation/controllers/reactions.controller.ts
  backend/src/automation/controllers/services.controller.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/default.reaction.service.ts
  backend/src/automation/services/services.service.ts
Labels: ✨ enhancement

#82 merge(feat/library_page): merge "feat/library_page" into "dev"
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/app/(protected)/(tabs)/library.tsx
  frontend/app/(protected)/Create/action/effect.tsx
  frontend/app/(protected)/Create/action/form.tsx
  frontend/app/(protected)/Create/reaction/effect.tsx
  frontend/app/(protected)/Create/reaction/form.tsx
  frontend/app/_layout.tsx
  frontend/components/actionButton.tsx
  frontend/components/reactionButton.tsx
  frontend/context/appletContext.tsx
  frontend/context/appletListContext.tsx
Labels: ✨ enhancement

#86 merge(dev): fix/ci into dev
  .github/workflows/ar3m_ci.yml
Labels: ⚙️ build

#87 merge(feat/frontend/add_delete_button): merge "feat/frontend/add_delete_button" into dev
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/components/reactionButton.tsx
Labels: ✨ enhancement

#88 merge(dev): fix/port_expose into dev
  docker-compose.prod.yml
Labels: ⚙️ build

#89 merge(dev): merge applet-patch into dev
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.service.ts
  backend/src/automation/automation.module.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/spotify.action.service.ts
Labels: ✨ enhancement

#91 merge(dev): merge applet-patch into dev
  backend/src/webhooks/webhook.service.ts
Labels: ✨ enhancement

#90 merge(main): dev into main
  .github/workflows/ar3m_ci.yml
  backend/package-lock.json
  backend/package.json
  backend/src/about/about.service.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/provider-dto.ts
  backend/src/automation/automation.module.ts
  backend/src/automation/controllers/actions.controller.ts
  backend/src/automation/controllers/reactions.controller.ts
  backend/src/automation/controllers/services.controller.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/default.reaction.service.ts
  backend/src/automation/services/services.service.ts
  backend/src/automation/services/spotify.action.service.ts
  backend/src/webhooks/webhook.service.ts
  docker-compose.prod.yml
  frontend/app.json
  frontend/app/(protected)/(tabs)/_layout.tsx
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/app/(protected)/(tabs)/library.tsx
  frontend/app/(protected)/Create/action/effect.tsx
  frontend/app/(protected)/Create/action/form.tsx
  frontend/app/(protected)/Create/reaction/effect.tsx
  frontend/app/(protected)/Create/reaction/form.tsx
  frontend/app/(protected)/helpService/HelpGetting Started.tsx
  frontend/app/(protected)/helpService/HelpGithub.tsx
  frontend/app/(protected)/helpService/Helppage.tsx
  frontend/app/(protected)/helpcenter.tsx
  frontend/app/(protected)/services.tsx
  frontend/app/_layout.tsx
  frontend/components/GettingStarted.tsx
  frontend/components/actionButton.tsx
  frontend/components/descriptionHelpButton.tsx
  frontend/components/generalHelp.tsx
  frontend/components/header.tsx
  frontend/components/reactionButton.tsx
  frontend/context/appletContext.tsx
  frontend/context/appletListContext.tsx
  frontend/context/serviceListContext.tsx
  frontend/eas.json
  frontend/package-lock.json
  frontend/package.json
Labels: ✨ enhancement, 🔨 fix, ⚙️ build

#92 merge(dev): fix/ci into dev
  .github/workflows/ar3m_ci.yml
Labels: 🔨 fix

#97 merge(main): merge dev into main to apply ci-cd fix
  .github/workflows/ar3m_ci.yml
  backend/src/applets/applets.service.ts
Labels: 📝 documentation, ✨ enhancement, 🔨 fix

#98 feat(dev): merge actions-github into dev
  backend/src/automation/services/default.action.service.ts
  backend/src/webhooks/webhook.service.ts
Labels: 📝 documentation, ✨ enhancement

#99 merge(dev): merge refactor/applet-name into dev
  backend/src/applets/applets.service.ts
  backend/src/applets/dto/applets.dto.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/schemas/applet.schema.ts
Labels: ✨ enhancement

#101 merge(dev): merge (feat/front/add_applet_name) into (dev)
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/app/(protected)/(tabs)/library.tsx
  frontend/app/(protected)/Create/action/effect.tsx
  frontend/app/(protected)/Create/action/form.tsx
  frontend/app/(protected)/Create/reaction/effect.tsx
  frontend/app/(protected)/Create/reaction/form.tsx
  frontend/context/appletContext.tsx
  frontend/context/appletListContext.tsx
Labels: ✨ enhancement

#102 merge(dev): feature/mail_send into dev
  backend/package-lock.json
  backend/package.json
  backend/src/auth/auth.service.ts
  backend/src/auth/strategies/google.strategy.ts
  backend/src/automation/automation.module.ts
  backend/src/automation/services/default.reaction.service.ts
  backend/src/automation/services/discord.reaction.service.ts
  backend/src/automation/services/google.reaction.service.ts
  backend/src/automation/services/spotify.action.service.ts
  backend/src/webhooks/webhook.service.ts
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/components/signup.tsx
  frontend/context/appletListContext.tsx
  frontend/context/serviceListContext.tsx
Labels: ✨ enhancement

#106 merge(dev): merge feat/github-area into dev
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/github.action.service.ts
  backend/src/webhooks/webhook.controller.ts
  backend/src/webhooks/webhook.service.ts
Labels: 📝 documentation, ✨ enhancement

#107 merge(dev) merge build/apk2 into dev
  .env.template
  docker-compose.prod.yml
  docker-compose.yml
  frontend/Dockerfile
  frontend/Dockerfile.android
  frontend/apkurl.sh
  frontend/app.json
  frontend/eas.json
  frontend/package-lock.json
  frontend/package.json
  frontend/webpack.config.js
Labels: ⚙️ build

#109 merge(dev): merge feat/github-area into dev
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/github.action.service.ts
  backend/src/webhooks/webhook.controller.ts
  backend/src/webhooks/webhook.service.ts
Labels: ✨ enhancement

#111 merge(dev): merge github-area into dev
  backend/src/automation/automation.module.ts
  backend/src/automation/services/github.reaction.service.ts
  backend/src/webhooks/webhook.service.ts
Labels: 🔨 fix

#113 merge(dev): merge feat/github-area into dev
  backend/src/automation/services/default.reaction.service.ts
  backend/src/automation/services/github.reaction.service.ts
Labels: ✨ enhancement

#114 merge(dev) merge doc auth into dev
  .gitignore
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/dto/forgot-password.dto.ts
  backend/src/auth/dto/provider-dto.ts
  backend/src/auth/dto/reset-password.dto.ts
  backend/src/auth/services/local-auth.service.ts
  backend/src/auth/services/provider-auth.service.ts
  frontend/Dockerfile.android
  frontend/eas.json
Labels: ✨ enhancement

#115 merge (dev): merge (feature/front_upgrade) into dev
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/app/(protected)/Create/action/effect.tsx
  frontend/app/(protected)/Create/action/form.tsx
  frontend/app/(protected)/Create/reaction/effect.tsx
  frontend/app/(protected)/Create/reaction/form.tsx
  frontend/app/(protected)/Create/services.tsx
  frontend/app/(protected)/services.tsx
  frontend/components/actionButton.tsx
  frontend/components/generalHelp.tsx
  frontend/components/reactionButton.tsx
  frontend/package-lock.json
Labels: ✨ enhancement

#116 merge(dev): merge github-area into dev
  backend/src/automation/services/default.reaction.service.ts
  backend/src/automation/services/github.reaction.service.ts
Labels: ✨ enhancement

#119 merge(dev): feature/twitch_live into dev
  backend/src/automation/automation.module.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/default.reaction.service.ts
  backend/src/automation/services/twitch.action.service.ts
  backend/src/webhooks/webhook.controller.ts
  backend/src/webhooks/webhook.service.ts
  frontend/apkurl.sh
  frontend/eas.json
Labels: ✨ enhancement

#120 merge(dev) merge doc/auth in to dev
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/auth.service.ts
  backend/src/auth/services/discord-provider.service.ts
  backend/src/auth/services/github-provider.service.ts
  backend/src/auth/services/google-provider.service.ts
  backend/src/auth/services/interfaces/provider.interface.ts
  backend/src/auth/services/local-auth.service.ts
  backend/src/auth/services/microsoft-provider.service.ts
  backend/src/auth/services/provider-auth.service.ts
  backend/src/auth/services/providers.service.ts
  backend/src/auth/services/spotify-provider.service.ts
  backend/src/auth/services/twitch-provider.service.ts
  backend/src/auth/strategies/discord.strategy.ts
  backend/src/auth/strategies/github.startegy.ts
  backend/src/auth/strategies/google.strategy.ts
  backend/src/automation/automation.module.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/default.reaction.service.ts
  backend/src/automation/services/google.reaction.service.ts
  backend/src/automation/services/leagueoflegends.action.service.ts
  env/back.env.example
  frontend/eas.json
  frontend/package-lock.json
  frontend/package.json
Labels: ✨ enhancement

#121 merge(dev) merge doc/auth into dev
  frontend/Dockerfile.android
Labels: 🔨 fix, ⚙️ build

#122 merge(dev) merge doc/auth into dev
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/auth/services/microsoft-provider.service.ts
  backend/src/auth/services/providers.service.ts
  backend/src/auth/services/strava-provider.service.ts
  backend/src/automation/automation.module.ts
  backend/src/automation/controllers/services.controller.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/default.reaction.service.ts
  backend/src/automation/services/google.reaction.service.ts
  backend/src/automation/services/leagueoflegends.action.service.ts
  backend/src/automation/services/outlook.action.service.ts
  backend/src/schemas/log.schema.ts
Labels: ✨ enhancement

#124 merge(dev) merge doc/auth into dev
  backend/src/auth/auth.controller.ts
  backend/src/auth/auth.module.ts
  backend/src/automation/automation.module.ts
  backend/src/automation/controllers/services.controller.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/outlook.action.service.ts
  backend/src/log/log.module.ts
  backend/src/log/log.service.ts
  backend/src/webhooks/webhook.controller.ts
  backend/src/webhooks/webhook.service.ts
Labels: ✨ enhancement, 🔨 fix

#123 merge(dev): merge "feat/front_fix" into dev
  frontend/app/(auth)/auth/callback.tsx
  frontend/app/(protected)/(tabs)/create.tsx
  frontend/app/(protected)/(tabs)/library.tsx
  frontend/app/(protected)/Create/action/form.tsx
  frontend/app/(protected)/account.tsx
  frontend/app/(protected)/helpcenter.tsx
  frontend/app/(protected)/services.tsx
  frontend/components/confirmServerAddress.ts
  frontend/components/generalHelp.tsx
  frontend/components/login.test.tsx
  frontend/components/login.test2.tsx
  frontend/components/login.tsx
  frontend/components/signup.tsx
  frontend/context/appletContext.tsx
  frontend/context/appletListContext.tsx
  frontend/context/serviceListContext.tsx
  frontend/hooks/useAuth.ts
Labels: ✨ enhancement, 🔨 fix

#125 merge(dev): merge "feat/frontend/theme" into dev
  frontend/app/(protected)/(tabs)/profile.tsx
  frontend/app/_layout.tsx
  frontend/context/themeContext.tsx
Labels: ✨ enhancement

#126 merge (dev) merge Doc/auth into dev
  backend/src/auth/auth.module.ts
  backend/src/auth/services/facebook-provider.service.ts
  backend/src/auth/services/microsoft-provider.service.ts
  backend/src/auth/services/providers.service.ts
  backend/src/automation/automation.module.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/default.reaction.service.ts
  backend/src/automation/services/leagueoflegends.action.service.ts
  backend/src/automation/services/microsoft.reaction.service.ts
  backend/src/automation/services/outlook-emails.action.service.ts
  backend/src/automation/services/outlook-events.action.service.ts
  backend/src/automation/services/outlook.action.service.ts
  backend/src/automation/services/services.service.ts
  backend/src/automation/services/spotify.action.service.ts
  backend/src/automation/services/youtube.action.service.ts
  backend/src/utils/string-utils.ts
  backend/src/webhooks/webhook.controller.ts
  backend/src/webhooks/webhook.service.ts
Labels: ✨ enhancement

#127 merge(dev): merge "frontend/register" into dev
  frontend/app/(auth)/register.tsx
  frontend/components/signup.tsx
  frontend/context/appletListContext.tsx
Labels: 🔨 fix

#129 merge(dev) merge doc/auth into dev
  .env.example
  backend/.env.example
  backend/src/automation/services/services.service.ts
  env/back.env.example
  frontend/apkurl.sh
Labels: ✨ enhancement

#130 merge(dev) merge doc/auth into dev
  backend/.env.example
  env/back.env.example
  frontend/.env.template
  frontend/app/(protected)/account.tsx
  frontend/hooks/useAuth.ts
Labels: 🔨 fix

#131 merge(dev): merge docs/readmi_api into dev
  backend/src/automation/services/discord.reaction.service.ts
  docs/README_API.md
Labels: 📝 documentation, 🔨 fix

#133 merge(dev) merge fix/apk into dev
  frontend/app.json
  frontend/app/(auth)/register.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/routes/protectedRoute.tsx
Labels: 🔨 fix

#135 merge (dev) merge fix/apk into dev
  backend/.env.example
  backend/src/automation/automation.module.ts
  backend/src/automation/services/default.action.service.ts
  backend/src/automation/services/leagueoflegends.action.service.ts
  backend/src/automation/services/outlook-emails.action.service.ts
  backend/src/automation/services/outlook-events.action.service.ts
  backend/src/automation/services/outlook.action.service.ts
  backend/src/automation/services/youtube.action.service.ts
Labels: ✨ enhancement
